In [10]:
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# 1. Let’s attempt to predict the survival of a horse based on various observed medical conditions. Load the data from ‘horses.csv’ and observe whether it contains missing values.

In [13]:
df_horses = pd.read_csv('horse.csv')
df_horses.isnull()

,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,...,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,False,False,False,False,False,False,False,False,True,False,...,False,False,True,True,False,False,False,False,False,False
1,False,False,False,False,False,False,True,True,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,True,False,False,...,False,False,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,False,False,False,True,False,False,False,True,False,False,...,False,False,True,True,False,False,False,False,False,False
295,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
296,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,False,False,False,False,False,False
297,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
298,False,False,False,False,False,False,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False

# 2. This dataset contains many categorical features, replace them with label encoding.

In [14]:
df_horses

,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,...,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,no,adult,530101,38.5,66.0,28.0,cool,reduced,NaN,more_3_sec,...,45.0,8.4,NaN,NaN,died,no,11300,0,0,no
1,yes,adult,534817,39.2,88.0,20.0,NaN,NaN,pale_cyanotic,less_3_sec,...,50.0,85.0,cloudy,2.0,euthanized,no,2208,0,0,no
2,no,adult,530334,38.3,40.0,24.0,normal,normal,pale_pink,less_3_sec,...,33.0,6.7,NaN,NaN,lived,no,0,0,0,yes
3,yes,young,5290409,39.1,164.0,84.0,cold,normal,dark_cyanotic,more_3_sec,...,48.0,7.2,serosanguious,5.3,died,yes,2208,0,0,yes
4,no,adult,530255,37.3,104.0,35.0,NaN,NaN,dark_cyanotic,more_3_sec,...,74.0,7.4,NaN,NaN,died,no,4300,0,0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,yes,adult,533886,NaN,120.0,70.0,cold,NaN,pale_cyanotic,more_3_sec,...,55.0,65.0,NaN,NaN,euthanized,no,3205,0,0,no
295,no,adult,527702,37.2,72.0,24.0,cool,increased,pale_cyanotic,more_3_sec,...,44.0,NaN,serosanguious,3.3,euthanized,yes,2208,0,0,yes
296,yes,adult,529386,37.5,72.0,30.0,cold,reduced,pale_cyanotic,less_3_sec,...,60.0,6.8,NaN,NaN,died,yes,3205,0,0,no
297,yes,adult,530612,36.5,100.0,24.0,cool,reduced,pale_pink,less_3_sec,...,50.0,6.0,serosanguious,3.4,lived,yes,2208,0,0,yes
298,yes,adult,534618,37.2,40.0,20.0,NaN,NaN,NaN,NaN,...,36.0,62.0,clear,1.0,euthanized,no,6112,0,0,no

In [16]:
categorical_columns= ['surgery','temp_of_extremities','peripheral_pulse','mucous_membrane',
                      'capillary_refill_time','abdomo_appearance','outcome','surgical_lesion','cp_data']

In [21]:
le = LabelEncoder()
df_horses_enc = df_horses.copy()
for i in range(len(categorical_columns)):
    #print(categorical_columns[i])
    df_horses_enc[categorical_columns[i]] = LabelEncoder().fit_transform(df_horses_enc[categorical_columns[i]])
df_horses_enc

,surgery,age,hospital_number,rectal_temp,pulse,respiratory_rate,temp_of_extremities,peripheral_pulse,mucous_membrane,capillary_refill_time,...,packed_cell_volume,total_protein,abdomo_appearance,abdomo_protein,outcome,surgical_lesion,lesion_1,lesion_2,lesion_3,cp_data
0,0,0,125,23,17,16,1,3,6,2,...,21,36,3,37,0,0,55,0,0,0
1,1,0,214,30,28,9,4,4,4,1,...,26,77,1,6,1,0,13,0,0,0
2,0,0,140,21,3,13,2,2,5,1,...,8,19,3,37,2,0,0,0,0,1
3,1,1,264,29,50,36,0,2,2,2,...,24,24,2,29,0,1,13,0,0,1
4,0,0,133,11,34,20,4,4,2,2,...,48,26,3,37,0,0,36,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,1,0,174,40,39,33,0,4,4,2,...,31,62,3,37,1,0,25,0,0,0
295,0,0,15,10,20,13,1,1,4,2,...,20,80,2,16,1,1,13,0,0,1
296,1,0,84,13,20,17,0,3,4,1,...,36,20,3,37,0,1,25,0,0,0
297,1,0,155,4,33,13,1,3,5,1,...,26,12,2,17,2,1,13,0,0,1
298,1,0,204,10,3,9,4,4,6,3,...,11,59,0,1,1,0,44,0,0,0

# 3. Replace the missing values by the most frequent value in each column.

In [23]:
df_horses_enc = df_horses_enc.apply(lambda x: x.fillna(x.value_counts().index[0]))

In [26]:
#test train split
X= df_horses_enc.drop('cp_data', axis=1)
y=df_horses_enc.cp_data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

# 4. Fit a decision tree classifier and observe the accuracy.

In [30]:
model_dt = DecisionTreeClassifier()
model_dt.fit(X_train,y_train)
y_predict_dt = model_dt.predict(X_test)
print('Accuracy Score for Decision Tree is', accuracy_score(y_test,y_predict_dt))

Accuracy Score for Decision Tree is 0.7833333333333333

# 5. Fit a random forest classifier and observe the accuracy.

In [32]:
model_rf = RandomForestClassifier()
model_rf.fit(X_train,y_train)
y_predict_rf = model_rf.predict(X_test)
print('Accuracy Score for Random Forest is', accuracy_score(y_test,y_predict_rf))

Accuracy Score for Random Forest is 0.8666666666666667