In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [4]:
data_train = pd.read_csv('train.csv')
data_train.head()

,id,species,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
0,1,Acer_Opalus,0.007812,0.023438,0.023438,0.003906,0.011719,0.009766,0.027344,0.0,...,0.007812,0.000000,0.002930,0.002930,0.035156,0.0,0.0,0.004883,0.000000,0.025391
1,2,Pterocarya_Stenoptera,0.005859,0.000000,0.031250,0.015625,0.025391,0.001953,0.019531,0.0,...,0.000977,0.000000,0.000000,0.000977,0.023438,0.0,0.0,0.000977,0.039062,0.022461
2,3,Quercus_Hartwissiana,0.005859,0.009766,0.019531,0.007812,0.003906,0.005859,0.068359,0.0,...,0.154300,0.000000,0.005859,0.000977,0.007812,0.0,0.0,0.000000,0.020508,0.002930
3,5,Tilia_Tomentosa,0.000000,0.003906,0.023438,0.005859,0.021484,0.019531,0.023438,0.0,...,0.000000,0.000977,0.000000,0.000000,0.020508,0.0,0.0,0.017578,0.000000,0.047852
4,6,Quercus_Variabilis,0.005859,0.003906,0.048828,0.009766,0.013672,0.015625,0.005859,0.0,...,0.096680,0.000000,0.021484,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.031250

In [5]:
data_test = pd.read_csv('test.csv')
data_test.head()

,id,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,margin9,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
0,4,0.019531,0.009766,0.078125,0.011719,0.003906,0.015625,0.005859,0.0,0.005859,...,0.006836,0.000000,0.015625,0.000977,0.015625,0.0,0.0,0.000000,0.003906,0.053711
1,7,0.007812,0.005859,0.064453,0.009766,0.003906,0.013672,0.007812,0.0,0.033203,...,0.000000,0.000000,0.006836,0.001953,0.013672,0.0,0.0,0.000977,0.037109,0.044922
2,9,0.000000,0.000000,0.001953,0.021484,0.041016,0.000000,0.023438,0.0,0.011719,...,0.128910,0.000000,0.000977,0.000000,0.000000,0.0,0.0,0.015625,0.000000,0.000000
3,12,0.000000,0.000000,0.009766,0.011719,0.017578,0.000000,0.003906,0.0,0.003906,...,0.012695,0.015625,0.002930,0.036133,0.013672,0.0,0.0,0.089844,0.000000,0.008789
4,13,0.001953,0.000000,0.015625,0.009766,0.039062,0.000000,0.009766,0.0,0.005859,...,0.000000,0.042969,0.016602,0.010742,0.041016,0.0,0.0,0.007812,0.009766,0.007812

In [7]:
def encoder(data):
    labelencoder = LabelEncoder()
    data["species"] = labelencoder.fit_transform(data["species"])
    data.head()
    return data

data_train_encoded = encoder(data_train) 
data_train_encoded.head()

,id,species,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
0,1,3,0.007812,0.023438,0.023438,0.003906,0.011719,0.009766,0.027344,0.0,...,0.007812,0.000000,0.002930,0.002930,0.035156,0.0,0.0,0.004883,0.000000,0.025391
1,2,49,0.005859,0.000000,0.031250,0.015625,0.025391,0.001953,0.019531,0.0,...,0.000977,0.000000,0.000000,0.000977,0.023438,0.0,0.0,0.000977,0.039062,0.022461
2,3,65,0.005859,0.009766,0.019531,0.007812,0.003906,0.005859,0.068359,0.0,...,0.154300,0.000000,0.005859,0.000977,0.007812,0.0,0.0,0.000000,0.020508,0.002930
3,5,94,0.000000,0.003906,0.023438,0.005859,0.021484,0.019531,0.023438,0.0,...,0.000000,0.000977,0.000000,0.000000,0.020508,0.0,0.0,0.017578,0.000000,0.047852
4,6,84,0.005859,0.003906,0.048828,0.009766,0.013672,0.015625,0.005859,0.0,...,0.096680,0.000000,0.021484,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.031250

In [9]:
#Extractcing fatures and target variable and splitting into train and test dataset

X = data_train_encoded.iloc[:,1:]
y = data_train_encoded["species"]
X_train, X_test, y_train, y_test  = train_test_split(X, y, random_state = 42, test_size = 0.20)

# Random Forest Classifier

In [16]:
# Checking best params for Random Forest

model_rf = RandomForestClassifier()

param_grid = { 
    'n_estimators': [100, 200],
    'max_features': ['auto', 'sqrt', 'log2'],
    'criterion' : ["gini", "entropy"]
}

CV_rfc = GridSearchCV(estimator=model_rf, param_grid=param_grid, cv= 5)
CV_rfc.fit(X_train, y_train)
print(CV_rfc.best_params_) 

# Found {'criterion': 'gini', 'max_features': 'sqrt', 'n_estimators': 200}

E:\MachineLearning\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"

{'criterion': 'gini', 'max_features': 'sqrt', 'n_estimators': 200}

In [18]:
# Fitting and Validating Random Forest

model_rf_final = RandomForestClassifier(criterion = 'gini', max_features = 'sqrt', n_estimators = 200)
model_rf_final.fit(X_train, y_train)

y_predict_rf = model_rf_final.predict(X_test)
print("Random Forest Accuracy Score : ", metrics.accuracy_score(y_predict_rf, y_test))

Radom Forest Accuracy Score :  0.9797979797979798

# Decision Tree Classifier

In [23]:
# Checking best params for Decision Tree
model_dt = DecisionTreeClassifier()

param_grid = { 
    'min_samples_split': [2, 3, 4],
    'max_depth': np.arange(2, 10),
    'criterion' : ["gini", "entropy"]
}

CV_dt = GridSearchCV(estimator=model_dt, param_grid=param_grid, cv= 5)
CV_dt.fit(X_train, y_train)
print(CV_dt.best_params_) 

#Found {'criterion': 'entropy', 'max_depth': 8, 'min_samples_split': 4}

E:\MachineLearning\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"

{'criterion': 'entropy', 'max_depth': 8, 'min_samples_split': 4}

In [24]:
# Fitting and Validating Decision Tree

model_dt_final = RandomForestClassifier(criterion = 'entropy', max_depth = 8, min_samples_split = 4)
model_dt_final.fit(X_train, y_train)

y_predict_dt = model_dt_final.predict(X_test)
print("Decision Tree Accuracy Score : ", metrics.accuracy_score(y_predict_dt, y_test))

Decision Tree Accuracy Score :  0.9747474747474747

# Naive Bayes Classifier

In [26]:
# Checking best params for Naive Bayes
model_nb = GaussianNB()

param_grid = { 
    'var_smoothing': np.logspace(0,-9, num=100)
}

CV_nb = GridSearchCV(estimator=model_nb, param_grid=param_grid, cv= 5)
CV_nb.fit(X_train, y_train)
print(CV_nb.best_params_) 

#Found {'var_smoothing': 0.0006579332246575676}

E:\MachineLearning\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"

{'var_smoothing': 0.0006579332246575676}

In [40]:
# Fitting and Validating Naive Bayes

model_nb_final = GaussianNB(var_smoothing = 0.0006579332246575676)
model_nb_final.fit(X_train, y_train)

y_predict_nb = model_nb_final.predict(X_test)
print("Naive Bayes Accuracy Score : ", metrics.accuracy_score(y_predict_nb, y_test))

Naive Bayes Accuracy Score :  1.0

# SVM Classifier

In [31]:
# Checking best params for SVM
model_svc = SVC()

param_grid = { 
    'C': [0.1, 1, 10, 100, 1000],
    'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
    'kernel': ['linear', 'poly', 'rbf', 'sigmoid']
}

CV_svc = GridSearchCV(estimator=model_svc, param_grid=param_grid, cv= 5)
CV_svc.fit(X_train, y_train)
print(CV_svc.best_params_) 

#Found {'C': 1, 'gamma': 1, 'kernel': 'linear'}

E:\MachineLearning\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"

{'C': 1, 'gamma': 1, 'kernel': 'linear'}

In [37]:
# Fitting and Validating SVM

model_svc_final = SVC(C = 1, gamma = 1, kernel = 'linear',probability=True)
model_svc_final.fit(X_train, y_train)

y_predict_svc = model_svc_final.predict(X_test)
print("Support Vector Machine Accuracy Score : ", metrics.accuracy_score(y_predict_svc, y_test))

Support Vector Machine Accuracy Score :  1.0